#if !canImport(ObjectiveC)
import XCTest

extension SyslogLogHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SyslogLogHandlerTests = [
        ("testHelloWorld", testHelloWorld),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SyslogLogHandlerTests.__allTests__SyslogLogHandlerTests),
    ]
}
#endif
